In [1]:
import pandas as pd 
import numpy as np
from sklearn.feature_selection import VarianceThreshold
from numpy.random import seed, randn
from numpy import mean, std, percentile, nan, isnan
from sklearn.impute import SimpleImputer


In [2]:
df= pd.read_csv("iris.csv")
print("avant suppression des données on a:")
print(df.shape)
#les doublons
dups = df.duplicated()

#affichage des doublons
print("les doublons")
print(df[dups])

#suppression des doublons
df.drop_duplicates(inplace=True)
print("apres suppression des données on a:")
print(df.shape)

avant suppression des données on a:
(149, 5)
les doublons
     5.1  3.5  1.4  0.2     Iris-setosa
33   4.9  3.1  1.5  0.1     Iris-setosa
36   4.9  3.1  1.5  0.1     Iris-setosa
141  5.8  2.7  5.1  1.9  Iris-virginica
apres suppression des données on a:
(146, 5)


In [3]:
### 2

df2= pd.read_csv("oil-spill.csv")
data= df.values

x, y= data[:, :-1], data[:,-1]
transform= VarianceThreshold()
x_sel= transform.fit_transform(x)

#par défaut la variance est null
print(len(x_sel))
print(x)

146
[[4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.0 1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.

In [19]:
# 3
seed(2)

dt= 50 + 5*randn(10000)
moy, ecart= mean(dt), std(dt)

lower, upper= moy-3*ecart, moy+3*ecart
outliers=np.array([out for out in dt if out<lower or out>upper])
print("total des outliers")
print(len(outliers))

outliers_removed= [el for el in dt if el not in outliers]

total des outliers
34


9966

In [23]:
#question 4
q25= percentile(dt, 25)
q75= percentile(dt, 75)
iqr=q75-q25
cutt_off= 1.5 * iqr
low, up= q25-cutt_off, q75+cutt_off
out_removed= [val for val in dt if val>lower and val<upper]
len(out_removed)

9966

In [57]:
#question 5
dataset= pd.read_csv("pima-indians-diabetes.csv", header=None)
dataset.replace(0., nan, inplace=True)
print("taille avant suppression: ", dataset.shape)
dataset.dropna(inplace=True)
print("taille après suppression: ", dataset.shape)


taille avant suppression:  (768, 9)
taille après suppression:  (111, 9)


In [65]:
#question 6
dataframe= pd.read_csv("horse-colic.csv", header=None, na_values="?")
for i in range(dataframe.shape[1]):
    print("total de nan de la colonne ",i)
    print(dataframe[i].isna().sum())

total nan of column  0
1
total nan of column  1
0
total nan of column  2
0
total nan of column  3
60
total nan of column  4
24
total nan of column  5
58
total nan of column  6
56
total nan of column  7
69
total nan of column  8
47
total nan of column  9
32
total nan of column  10
55
total nan of column  11
44
total nan of column  12
56
total nan of column  13
104
total nan of column  14
106
total nan of column  15
247
total nan of column  16
102
total nan of column  17
118
total nan of column  18
29
total nan of column  19
33
total nan of column  20
165
total nan of column  21
198
total nan of column  22
1
total nan of column  23
0
total nan of column  24
0
total nan of column  25
0
total nan of column  26
0
total nan of column  27
0


In [78]:
dt_frame= dataframe.values
x= dt_frame[:, [i for i in range(28) if i!= 23]]
y= dt_frame[:, 23]
imputer= SimpleImputer(strategy="mean")
imputer.fit(x)
xtrans= imputer.transform(x)

naX=isnan(x).sum()
naXtrans= isnan(xtrans).sum()
